version: "3"

services:
    api:
        container_name: restaurante-34-api
        hostname: restaurante-34-api
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3001:3001"
        expose:
            - 3001
        environment:
            DATABASE_URL: postgresql://yuri:fX2Vdw9De@restaurant-34.c392otfqbduq.us-east-1.rds.amazonaws.com:5432/db_produto
        volumes:
            - pg_data:/var/lib/postgresql/data
        networks:
            - default
        restart: always


volumes:
    pg_data:
