name: "QA Pipeline"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  qa:
    if: github.event_name == 'pull_request'
    name: "Project Tests"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Configure Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install Deps
        run: npm install

      - name: Execute Tests
        run: npm run test

      - name: Execute Tests BDD
        run: |
          docker run --name db_produto -e POSTGRES_PASSWORD=1234 -d postgres:latest
          docker ps
          export DATABASE_URL=postgresql://postgres:1234@localhost:5432/postgres
      
      - name: Find Docker Host IP
        uses: addnab/docker-run-action@v1
        with:
          image: postgres:latest
          run: apk update > /dev/null && apk add iproute2 > /dev/null && ip -4 route show default | cut -d' ' -f3

      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.javascript.typescript=true
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.exclusions=**/node_modules/**,**/tests/**,**/dist/**,**/tests/**,src/routes.ts,src/server.ts,docker-compose.yaml,Dockerfile,**/manifests/**,commitlint.config.js
            -Dsonar.javascript.typescript.lcov.reportPaths=coverage/lcov.info